/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.hibernate.hibernate.core)
    api(libs.org.hsqldb.hsqldb)
    api(libs.com.sparkjava.spark.core)
    api(libs.junit.junit)
    api(libs.org.junit.jupiter.junit.jupiter)
    api(libs.org.apache.commons.commons.lang3)
}

group = "org.example"
version = "1.0-SNAPSHOT"
description = "lab1"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
